### ISSUE TITLE
How to build .jar from source code?

### ISSUE THREAD

**Issue by khoazero123** [tomazas/ATCommandTester#2]
I'm newbie Java, someone can guide me how to build this project?

**Comment by tomazas** [comment]
Steps to build on Eclipse IDE:
1. Download source.
2. Open in Eclipse IDE via File->Import->General->Existing Projects into Workspace.
3. Select the source folder, click Finish.
4. Right click on imported project.
5. Select Run As -> Java Application, choose "ATCommandTester" and OK.
6. Once the application launches - close it.
7. Now right-click the project again.
8. Select Export->Java->Runnable JAR file.
9. Select launch configuration "ATCommandTester" and export destination filename, click Finish.
10. If everything goes well, the JAR file will be at the specified destination.
Enjoy!

**Comment by khoazero123** [comment]
Thank you very much. It work :)
