### ISSUE TITLE
Port search not working on win10

### ISSUE THREAD

**Issue by mahksy** [tomazas/ATCommandTester#4]
"find ports" does nothing, aswell as no manual selection of ports possible

**Comment by tomazas** [comment]
@mahksy Please give more information.

Do you launch using run_x32.bat or run_x64.bat on 64bit system?
What errors do you see in the cmd.exe window after running run_x64.bat and pressing Find Ports?

**Comment by mahksy** [comment]
@tomazas i ran the run_x64.bat via user cmd, not elevated rights, following errror occured:

`java.lang.UnsatisfiedLinkError: C:\Users\mahksy\Downloads\ATCommandTester-master\runtime\windows\x64\rxtxSerial.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform thrown while loading gnu.io.RXTXCommDriver`

**Comment by tomazas** [comment]
You need to launch "run_x32.bat" instead since your system is 32-bit.

**Comment by mahksy** [comment]
```
C:\Users\mahksy>set pro
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
PROCESSOR_LEVEL=23
PROCESSOR_REVISION=7100
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G

```
I'm sure this is a 64 bit machine, just tried x32, runs just fine, no idea why that is.

**Comment by tomazas** [comment]
Thanks for the clarification.
Looks like this is RXTX library implementation specific. The 32-bit library works for both 32 & 64 bit.
