### ISSUE TITLE
Program closes unexpectedly

### ISSUE THREAD

**Issue by eladva** [tomazas/ATCommandTester#5]
Hello,

I hope this Github repository is still alive :-)

1. I press on "find ports".
2. select the com from the list.
3. press connect.
4. program writes "no port is connected" and crashes.

attached a log file 
[hs_err_pid10072.log](https://github.com/tomazas/ATCommandTester/files/5958879/hs_err_pid10072.log)

Please advise, Thanks!

**Comment by tomazas** [comment]
The repo is just for storing the project with no intention of active development.

Looks like an issue with RXTX library.
I would suggest updating the library or trying newer Java 1.8+ version.

**Comment by eladva** [comment]
Ah, O.K, Thanks @tomazas for your prompt response.

Updating Java didn't help.
what do you mean, how do I update the library?

**Comment by tomazas** [comment]
The runtime/windows/OS-bits/ contain rxtx library *.dll files. 
These dll files need to be updated to latest ones downloaded from http://fizzed.com/oss/rxtx-for-java
Once this is done, you might try again.

**Comment by eladva** [comment]
I updated the files from the link you gave me, and it still doesn't work.
before the command line closes, this is what's written there:
![image](https://user-images.githubusercontent.com/28383173/108093148-14b0ed00-7086-11eb-8a07-651ea7ea2297.png)

Do you have any more ideas?
Thanks! 😀

**Comment by tomazas** [comment]
Have you also tried the updated libraries with newer Java version? I still see you are using Java v1.8 in tests.
This problem is inside the native RXTX .dll library, not something that can be fixed in the ATCommandTester.

**Comment by mariocondesantos** [comment]
[hs_err_pid6612.log](https://github.com/tomazas/ATCommandTester/files/6872751/hs_err_pid6612.log)

i have equal proble....

Windows 10 64x

**Comment by tomazas** [comment]
Nothing can be done here. Better raise an issue to RXTX library creators.
